### ISSUE TITLE
Hide Image

### ISSUE THREAD

**Issue by dkwiebe** [alephcom/MusicPlayer#2]
![image](https://user-images.githubusercontent.com/1034679/160887330-5e88e2dd-e1e8-433b-acd1-bbfaef7ba705.png)

We don't want this image shown when it starts to play.

**Comment by dkwiebe** [comment]
We could control this in the .env file.  Have it default to the current setting but if it's set to "False" then don't display an image.  If it's set to a URL then could we embed that image?

**Comment by collab-smart** [comment]
Hi @dkwiebe 
I finished this issue (check below image). If that's fine, I will commit changes.
Should I make a commit in new branch or Can I push commit to master branch directly?

![image](https://user-images.githubusercontent.com/63889804/161056332-5d4b483a-914a-4395-b7e7-fb69a4ed69f5.png)

**Comment by dkwiebe** [comment]
Please make the commit in a new branch.  Thank you.

**Comment by collab-smart** [comment]
Please check this 2-hide-image branch.
You can set SONG_THUMBNAIL_IMAGE (Image URL) environment variable inside .env file.
If it is empty string then start streaming without image and if it exists then start with image.
![image](https://user-images.githubusercontent.com/63889804/161084376-eb04e66a-e6f3-41bd-8dd3-8b493238b19b.png)
