### ISSUE TITLE
Add Logging

### ISSUE THREAD

**Issue by dkwiebe** [alephcom/MusicPlayer#3]
If it's not a huge amount of work, I'd like to be able to log to files and ideally to be able to rotate logs.  Logging to syslog would be an option as well, I don't really have a preference but I'd like to be able to control this setting from the .env file.

**Comment by collab-smart** [comment]
Hi @dkwiebe 
Yeah, that's possible.
Which logs are you going to track?

**Comment by dkwiebe** [comment]
I'd like to log every request to the bot as well as all stream starts and stops.  They need to be logged in a format that we can parse and process them into Graylog.

**Comment by collab-smart** [comment]
@dkwiebe
 Do you have got sample log format?

**Comment by dkwiebe** [comment]
I don't.  Please log in JSON format and we can change if necessary.

**Comment by collab-smart** [comment]
Hi @dkwiebe 

I updated the branch and let me know feedback.(please update python dependency packages)

Below is configuration setting for logging.
![image](https://user-images.githubusercontent.com/63889804/162441388-627e4f47-96f1-4bdf-a636-3808e6205d8c.png)

If log enabled, it will create rotating requests.log and stream.log files inside logs folder of project root path.
The requests log is logging requests send to bot and the stream log is logging action of stream(start, skip).
Currently each log has 10MB of limit size and one of backup file.

Sample of requests.log format
`{
  "message": "!stream https://us-mo-kansascity-1.listentochurch.com:8443/5293803.mp3",
  "detail_message": {
    "_": "Message",
    "message_id": 321,
    "from_user": {
      "_": "User",
      "id": 5076603362,
      "is_self": false,
      "is_contact": false,
      "is_mutual_contact": false,
      "is_deleted": false,
      "is_bot": false,
      "is_verified": false,
      "is_restricted": false,
      "is_scam": false,
      "is_fake": false,
      "is_support": false,
      "first_name": "xxx",
      "last_name": "yyy",
      "status": "recently",
      "username": "xxx80",
      "language_code": "en"
    },
    "date": "2022-04-07 12:28:16",
    "chat": {
      "_": "Chat",
      "id": -1001658474330,
      "type": "supergroup",
      "is_verified": false,
      "is_restricted": false,
      "is_creator": false,
      "is_scam": false,
      "is_fake": false,
      "title": "music_private_group",
      "has_protected_content": false,
      "permissions": {
        "_": "ChatPermissions",
        "can_send_messages": true,
        "can_send_media_messages": true,
        "can_send_other_messages": true,
        "can_send_polls": true,
        "can_add_web_page_previews": true,
        "can_change_info": true,
        "can_invite_users": true,
        "can_pin_messages": true
      }
    },
    "mentioned": false,
    "scheduled": false,
    "from_scheduled": false,
    "has_protected_content": false,
    "text": "!stream https://us-mo-kansascity-1.listentochurch.com:8443/5293803.mp3",
    "entities": [
      {
        "_": "MessageEntity",
        "type": "url",
        "offset": 8,
        "length": 62
      }
    ],
    "outgoing": false,
    "command": [
      "stream",
      "https://us-mo-kansascity-1.listentochurch.com:8443/5293803.mp3"
    ]
  }
}`

Sample of stream.log format
`{
  "message": "start_stream",
  "title": "Live Stream",
  "source": "https://us-mo-kansascity-1.listentochurch.com:8443/5293803.mp3"
}`
