### ISSUE TITLE
Control Bot via HTTP Post

### ISSUE THREAD

**Issue by dkwiebe** [alephcom/MusicPlayer#5]
Add support to control the bot via an HTTP POST.  Once the bot and user are added to a group, I'd like to be able to send the group id, connect (play/stream), and the URL to the bot and have it start or stop the music in the group.

**Comment by collab-smart** [comment]
Hi @dkwiebe 

You can check the branch now.
API server will start automatically. You can set API Server Port in env file (default is 24859).

Sample API request: 

     curl -d '{"chat_id" : -1001658474630,"message" : "!stream https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"}' -H 'Content-Type: application/json' -X POST http://localhost:24859
    
![image](https://user-images.githubusercontent.com/63889804/161557166-7accf34c-18da-4d8b-b3cd-bfd9d93f89a9.png)

**Comment by dkwiebe** [comment]
@smart95-git could you add basic auth to this as well?

**Comment by collab-smart** [comment]
@dkwiebe Sure, I will do it.

**Comment by dkwiebe** [comment]
@smart95-git, don't worry about authentication.  I'll control that in the reverse proxy.
