### ISSUE TITLE
Add support to look up url of music or video to play

### ISSUE THREAD

**Issue by dkwiebe** [alephcom/MusicPlayer#7]
For example, instead of sending the following:

```
!stream https://us-mo-kansascity-1.listentochurch.com:8443/5293803.mp3
```

I'd like to send this:

```
!stream LTC:9235230
```

Then I'd like the system to reach out via an HTTP GET to an endpoint specified in the .env file for the URL to play.  The code "LTC" in this case, should be specified in the .env file as well.  This should apply to both the audio and the video players and will allow us to pass credentials to the player without making them publicly visible in the channel.

An example GET would be:

https://test.com/api/stream/convert/LTC:9235230

and the system would return something like this:

```
{ "status": true, "url": "https://us-mo-kansascity-1.listentochurch.com:8443/5293803.mp3" }
```

or, if it failed:

```
{"status": false}
```

**Comment by collab-smart** [comment]
Hi @dkwiebe 

I updated the branch and you can check now.

![image](https://user-images.githubusercontent.com/63889804/161998884-80f62cbb-c013-46bc-af12-8c3ff4de6ddf.png)
